# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import healthy_pb2 as healthy__pb2


class HealthCheckServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckSecurity = channel.unary_unary(
                '/HealthCheckService/CheckSecurity',
                request_serializer=healthy__pb2.SecurityRequest.SerializeToString,
                response_deserializer=healthy__pb2.SecurityResponse.FromString,
                )


class HealthCheckServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckSecurity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthCheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckSecurity': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSecurity,
                    request_deserializer=healthy__pb2.SecurityRequest.FromString,
                    response_serializer=healthy__pb2.SecurityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HealthCheckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HealthCheckService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckSecurity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HealthCheckService/CheckSecurity',
            healthy__pb2.SecurityRequest.SerializeToString,
            healthy__pb2.SecurityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
